import pandas as pd
from components.constants import MOCK_DATA_PATH_LOCAL

def generate_mock_data() -> None:
	data = {
		'sequence': [
			'MSAWASEKKLLKEDDFQFGQEDLSANQSPPKEGFFAARKIFDLRDKPQLR',
			'MSAWASEKKLLKEDDFQFGQEDLSANQSPPKEGFFAARKIFDLRDKPQLRMSAWASEKKLLKEDDFQFGQEDLSANQSPPKEGFFAARKIFDLRDKPQLR',
			'MSAWASEKKLLKEDDFQFGQEDLSANQSPPKEGFFAARKIFDLRDKPQLRMSAWASEKKLLKEDDFQFGQEDLSANQSP',
		],
		'name': ['Seq1', 'Seq2', 'Seq3']    
	}

	df = pd.DataFrame(data)
	df.to_parquet(MOCK_DATA_PATH_LOCAL, index=False)
