import logging
import pandas as pd
from fondant.component import PandasTransformComponent
import iFeatureOmega_CLI.iFeatureOmegaCLI as iFO

# Set up logging
logger = logging.getLogger(__name__)


class IFeatureOmegaComponent(PandasTransformComponent):
	"""The IFeatureOmegaComponent class is a component that generates new features using iFeatureOmega."""

	def __init__(self, descriptors: list):
		self.descriptors = descriptors

	def transform(self, dataframe: pd.DataFrame) -> pd.DataFrame:
		"""Perform the transformation on the dataframe."""
		sequences = dataframe["sequence"].tolist()

		all_features = self.generate_all_features_names(sequences[0], dataframe)
		dataframe = pd.concat([dataframe, pd.DataFrame(columns=all_features)])
		dataframe = self.generate_ifeature_omega_values(sequences, dataframe)

		return dataframe

	def generate_ifeature_omega_values(self, sequences: list, dataframe: pd.DataFrame) -> pd.DataFrame:
		"""Generate the iFeatureOmega features for the sequences and add them to the dataframe."""

		for sequence in sequences:
			ifeature_omega_protein = self.create_ifo_protein(
				sequence, dataframe)
			for descriptor in self.descriptors:
				ifeature_omega_protein.get_descriptor(descriptor)
				df_ifeature_protein = ifeature_omega_protein.encodings
				dataframe.loc[dataframe["sequence"] == sequence,
							df_ifeature_protein.columns] = df_ifeature_protein.values[0]

		return dataframe

	def create_ifo_protein(self, sequence: str, dataframe: pd.DataFrame) -> iFO.iProtein:
		"""Create an iProtein object from a sequence."""
		# based on the sequence, give me the checksum_sequence in the dataframe
		file_name = dataframe.loc[dataframe["sequence"]
								== sequence, "sequence_checksum"].values[0]

		file_path = f"/{file_name}.txt"
		with open(file_path, "w") as file:
			file.write(f">{file_name}\n")
			file.write(sequence)

		return iFO.iProtein(file_path)

	def generate_all_features_names(self, sequence: str, dataframe: pd.DataFrame) -> list:
		"""Generate the names of all the features that will be generated by iFeatureOmega."""
		all_features = []

		single_protein = self.create_ifo_protein(sequence, dataframe)

		for descriptor in self.descriptors:
			single_protein.get_descriptor(descriptor)
			df_ifeature_protein = single_protein.encodings
			all_features.extend(df_ifeature_protein.columns)

		return all_features
